parameters:
    # Adds a fallback API KEYS if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(CONDUCTION_COMMONGROUND_BAG_APIKEY): 'Change me in your .env file'
    env(NLX_OUTWAY): true
    env(NLX_INWAY): false
        
    env(APP_COMMONGROUND_id): '' 
    env(APP_COMMONGROUND_KEY): '' 
    env(APP_APPLICATION_KEY): '' 
    env(APP_USER_KEY): ''  
    env(APP_ENV): '' 
    env(APP_VERSION): '' 
    env(APP_NAME): '' 
    env(APP_DOMAINS): '[]'      
    env(AUTH_PROVIDER_USER): '' 
    env(AUTH_PROVIDER_APPLICATION): '' 
    
    app_commonground_id: '%env(APP_COMMONGROUND_ID)%'  
    app_commonground_key: '%env(APP_COMMONGROUND_KEY)%'   
    app_application_key: '%env(APP_APPLICATION_KEY)%'   
    app_user_key: '%env(APP_USER_KEY)%'               
    app_env: '%env(APP_ENV)%'                     
    app_version: '%env(APP_VERSION)%'           
    app_name: '%env(APP_NAME)%'   
    app_domains: '%env(json:APP_DOMAINS)%'  
    auth_provider_user: '%env(AUTH_PROVIDER_USER)%'   
    auth_provider_application: '%env(AUTH_PROVIDER_APPLICATION)%'    
    
    common_ground.bag.location: 'https://bag.basisregistraties.overheid.nl/api/v1/'
    common_ground.bag.apikey: 'e8a95365-3078-4b41-990a-e3de43cecd36'

    common_ground.ac.location: 'https://ac.huwelijksplanner.online'
    common_ground.ac.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.as.location: 'https://as.zaakonline.nl'
    common_ground.as.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.bc.location: 'https://bc.huwelijksplanner.online'
    common_ground.bc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.brp.location: 'https://brp.huwelijksplanner.online'
    common_ground.brp.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.bs.location: 'https://bs.huwelijksplanner.online'
    common_ground.bs.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.cc.location: 'https://cc.huwelijksplanner.online'
    common_ground.cc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.irc.location: 'https://irc.huwelijksplanner.online'
    common_ground.irc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.lc.location: 'https://lc.huwelijksplanner.online'
    common_ground.lc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.ltc.location: 'https://ltc.huwelijksplanner.online'
    common_ground.ltc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.mrc.location: 'https://mrc.huwelijksplanner.online'
    common_ground.mrc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.orc.location: 'https://orc.huwelijksplanner.online'
    common_ground.orc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.pdc.location: 'https://pdc.huwelijksplanner.online'
    common_ground.pdc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.ptc.location: 'https://ptc.huwelijksplanner.online'
    common_ground.ptc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.vrc.location: 'https://vrc.huwelijksplanner.online'
    common_ground.vrc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.vtc.location: 'https://vtc.huwelijksplanner.online'
    common_ground.vtc.apikey: '%env(APP_COMMONGROUND_KEY)%'

    common_ground.wrc.location: 'https://wrc.huwelijksplanner.online'
    common_ground.wrc.apikey: '%env(APP_COMMONGROUND_KEY)%'
    
    common_ground.oas.type: service
    common_ground.oas.host: irc.zaakonline.nl
    common_ground.oas.servers:
            -
              description: Demo Omgeving
              url: 'http://proto.demo.common-ground.dev'       
    common_ground.oas.externalDocs:
            -
              description: OAS Documentatie
              url: 'http://proto.demo.common-ground.dev'  
    common_ground.oas.developers:
            -
              name: Conduction
              url: https://github.com/ConductionNL
              email: info@conduction.nl
            -
              name: Gemeente 's-Hertogenbosch
              url: https://github.com/gemeenteshertogenbosch
              email: info@s-hertogenbosch.nl/
            -
              name: Gemeente Utrecht
              url: https://github.com/GemeenteUtrecht
              email: info@utrecht.nl
    common_ground.oas.builds:
            -
              name: travis
              logo: https://travis-ci.org/api-platform/core.svg?branch=master
              url: https://travis-ci.org/api-platform/core
            -
              name: appveyor
              logo: https://ci.appveyor.com/api/projects/status/grwuyprts3wdqx5l?svg=true
              url: https://ci.appveyor.com/project/dunglas/dunglasapibundle
            -
              name: codecov
              logo: https://codecov.io/gh/api-platform/core/branch/master/graph/badge.svg
              url: https://codecov.io/gh/api-platform/core
            -
              name: SensioLabsInsight
              logo: https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93/mini.png
              url: https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93
            -
              name: Scrutinizer Code Quality
              logo: https://scrutinizer-ci.com/g/api-platform/core/badges/quality-score.png?b=master
              url: https://scrutinizer-ci.com/g/api-platform/core/?branch=master 

common_ground:      
    bag:
        # cashing is a common ground hot patato, from a data at the source perspective we don't want to duplicate data
        # but.... city and street names are not going to change regularly, so to prevent unnecessary api calls cashing makes sense
        #
        # Therefore we are going to allow cashing on the bag api
        #
        # Valid values:
        # - false (no cashing)
        # - integer (cash for given amount of milliseconds)
        # - a valid php datetime input (cash item deleted at that date), https://www.php.net/manual/en/function.strtotime.php
        cash:        
            nummeraanduiding: 604800000 # 1 week      
            woonplaats: 'January 1st Next Year' # By law Dutch localities only change in January the first      
            openbareruimte:  604800000 # 1 week      
            panden: 604800000 # 1 week
            verblijfsobject: 604800000 # 1 week
            ligplaatsen: 604800000 # 1 week
            standplaatsen: 604800000 # 1 week
        # Get your BAG api key at https://bag.basisregistraties.overheid.nl/restful-api, or by sending a email to dataplatform@kadaster.nl        
        apikey: '%env(CONDUCTION_COMMONGROUND_BAG_APIKEY)%' 
        # The default BAG api location, change this if yoy are using an NLX adaptor
        location: 'https://bag.basisregistraties.overheid.nl/api/v1/' 
        
