parameters:
    # Organisation stuff
    env(GOOGLE_TAG_MANAGER_ID): ''
    env(HUBSPOT_EMBED_CODE): ''
    env(CONTAINER_REGISTRY_BASE): ''
    env(CONTAINER_PROJECT_NAME): ''
    env(ORGANIZATION_NAME): ''
    env(ORGANIZATION_EMAIL_ADDRESS): ''    
    env(ORGANIZATION_COUNTRY_NAME): ''    
    env(ORGANIZATION_STATE): ''    
    env(ORGANIZATION_LOCALITY): ''    
    env(ORGANIZATION_UNIT_NAME): ''    
    env(APP_NAME): ''     
    env(APP_TITLE): ''     
    env(APP_LOGO): ''    
    env(APP_HOME): ''       
    env(APP_VERSION): ''     
    env(APP_ENV): ''         
    env(APP_DEBUG): ''   
    env(APP_CACHE): ''            
    env(APP_DOMAIN): ''       
    env(APP_SUBDOMAIN): ''    
    env(APP_DEMO): ''           
    env(APP_REPRO): ''       
    env(APP_CONTAINER): ''             
    env(APP_DESCRIPTION): ''           
    env(APP_TYPE): ''           
    env(AUTH_ENABLED): ''    
    env(AUTH_PROVIDER_USER): ''        
    env(AUTH_PROVIDER_APPLICATION): ''    
    env(AUDITTRAIL_ENABLED): ''    
    env(NOTIFICATION_ENABLED): ''    
    env(HEALTH_ENABLED): ''       
    env(TRUSTED_HOSTS): ''       
    env(TRUSTED_PROXIES): ''        
    env(NLX_OUTWAY): ''     
    env(NLX_INWAY): '' 
    env(APP_COMMONGROUND_ID): '' 
    env(APP_COMMONGROUND_KEY): '' 
    env(APP_APPLICATION_KEY): '' 
    env(APP_USER_KEY): '' 

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        google_tag_manager_id: '%env(GOOGLE_TAG_MANAGER_ID)%'
        hubspot_embed_code: '%env(HUBSPOT_EMBED_CODE)%'         
        
        container_registry_base: '%env(CONTAINER_REGISTRY_BASE)%'   
        container_project_name: '%env(CONTAINER_PROJECT_NAME)%'

        organization_name: '%env(ORGANIZATION_NAME)%'
        organization_email: '%env(ORGANIZATION_EMAIL_ADDRESS)%'
        organization_country: '%env(ORGANIZATION_COUNTRY_NAME)%'
        organization_state: '%env(ORGANIZATION_STATE)%'
        organization_locality: '%env(ORGANIZATION_LOCALITY)%'
        organization_unit: '%env(ORGANIZATION_UNIT_NAME)%'
        
        app_name: '%env(APP_NAME)%'
        app_title: '%env(APP_TITLE)%'
        app_logo: '%env(APP_LOGO)%'
        app_home: '%env(APP_HOME)%'
        app_version: '%env(APP_VERSION)%'
        app_env: '%env(APP_ENV)%'
        app_debug: '%env(APP_DEBUG)%'
        app_cache: '%env(APP_CACHE)%'
        app_domain: '%env(APP_DOMAIN)%'
        app_subdomain: '%env(APP_SUBDOMAIN)%'
        app_demo: '%env(APP_DEMO)%' 
        app_container: '%env(APP_CONTAINER)%'
        app_repro: '%env(APP_REPRO)%'
        app_description: '%env(APP_DESCRIPTION)%'
        app_type: '%env(APP_TYPE)%'
        
        app_auth: '%env(AUTH_ENABLED)%'        
        auth_provider_user: '%env(AUTH_PROVIDER_USER)%'        
        auth_provider_application: '%env(AUTH_PROVIDER_APPLICATION)%'        
        app_audittrail: '%env(AUDITTRAIL_ENABLED)%'        
        app_notification: '%env(NOTIFICATION_ENABLED)%'
        app_health: '%env(HEALTH_ENABLED)%'   
        
        app_commonground_id: '%env(APP_COMMONGROUND_ID)%'   
        app_commonground_key: '%env(APP_COMMONGROUND_KEY)%'   
        app_application_key: '%env(APP_APPLICATION_KEY)%'   
        app_user_key: '%env(APP_USER_KEY)%'               
        
        trusted_hosts: '%env(TRUSTED_HOSTS)%'
        trusted_proxies: '%env(TRUSTED_PROXIES)%'
        
        nlx_outway: '%env(NLX_OUTWAY)%'
        nlx_inway: '%env(NLX_INWAY)%'
    form_themes:
        - 'TbbcMoneyBundle:Form:fields.html.twig'
