apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  #namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  project_name: {{ .Values.settings.projectName | quote }}
  app-name: {{ .Values.settings.name | quote }}
  app-title: {{ .Values.settings.title | quote }}
  app-version: {{ .Values.settings.version | quote }}
  {{ if .Values.settings.id }}
  app-id: {{ .Values.settings.id | quote }}
  {{ end }}
  app-repro: {{ .Values.settings.repro | quote }}
  app-demo: {{ .Values.settings.demo | quote }}
  app-container: {{ .Values.settings.container | quote }}
  app-domain: {{ .Values.settings.domain | quote }} 
  app-domains-json: {{ .Values.settings.domainsJson | toJson | quote }}
  app-description: {{ .Values.settings.description | quote }}
  app-type: {{ .Values.settings.type | quote }}
  
  app-auth: {{ .Values.settings.authorisationEnabled | quote }}
  app-audittrail: {{ .Values.settings.audittrailEnabled | quote }}
  app-notification: {{ .Values.settings.notificationEnabled | quote }}
  app-health: {{ .Values.settings.healthEnabled | quote }}
  app-archive: {{ .Values.settings.archiveEnabled | quote }}
  
  organization-name: {{ .Values.settings.organisationName | quote }}
  organization-email: {{ .Values.settings.email | quote }}
  organization-country: {{ .Values.settings.country | quote }}
  organization-state: {{ .Values.settings.state | quote }}
  organization-locality: {{ .Values.settings.locality | quote }}
  organization-unit: {{ .Values.settings.unit | quote }}
  
  cache: {{ .Values.settings.cache | quote }}
  env: {{ .Values.settings.env | quote }}
  debug: {{ .Values.settings.debug | quote }}
  cors-allow-origin: {{ .Values.settings.corsAllowOrigin | quote }}
  trusted-proxies: {{ join "," .Values.settings.trustedProxies }}
  trusted-hosts: {{ .Values.settings.trustedHosts | quote }}
  php-service: {{ .Values.settings.name }}-{{ .Values.settings.env }}-php  
  varnish-url: {{ if .Values.varnish.enabled }}http://varnish{{ else }}{{ .Values.varnish.url | quote }}{{ end }}
  mercure-publish-url: {{ .Values.mercure.publishUrl | quote }}
  mercure-subscribe-url: {{ .Values.mercure.subscribeUrl | quote }}
