apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "name" . }}-{{ .Values.settings.env }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-ingress
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    {{- if eq .Values.settings.env "prod" }}
    - {{ .Values.settings.domain }}
    {{- else }}      
    - {{ .Values.settings.env }}.{{ .Values.settings.domain }}     
    {{- end }}    
    secretName: {{ include "name" . }}-certs
  rules:
#    - host: {{ .Values.settings.name }}.{{ .Values.settings.env }}.{{ .Values.settings.domain }}
#      http:
#        paths:
#          - backend:
#              serviceName: {{ include "name" . }}
#              servicePort: 80
    {{- if eq .Values.settings.env "prod" }}
    - host: {{ .Values.settings.domain }}
      http:
        paths:
          - path: /.well-known/*
            backend:
              serviceName: {{ include "name" . }}-letsencrypt
              servicePort: 80
          - path: /*
            backend:
              serviceName: {{ include "name" . }}
              servicePort: 80
    {{- else }}      
    - host: {{ .Values.settings.env }}.{{ .Values.settings.domain }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "name" . }}
              servicePort: 80
     {{- end }}
